### ISSUE TITLE
not able to query Items example

### ISSUE THREAD

**Issue by camous** [batjko/gql2sql#2]
I'm fairly new to graphql and I might be missing a major point.

I've configured successfully a connection to an SQL database, validated by npm test
![image](https://user-images.githubusercontent.com/8566299/52864988-ca65a000-313b-11e9-98c0-d5c638acaeb0.png)

target table
![image](https://user-images.githubusercontent.com/8566299/52865127-23cdcf00-313c-11e9-9396-97357fa850ab.png)

when testing with graphiQL
![image](https://user-images.githubusercontent.com/8566299/52865225-68596a80-313c-11e9-8295-4c477fcd0526.png)

I'm pretty sure I'm missing an important point but wasn't able to find it. Any help would be much appreciated.

**Comment by batjko** [comment]
Hi there,

The code base is 3 years old, so it's about as alien to me as it is to you, I'm afraid.
My initial guess would be that your dependencies have updated versions which broke the creation of the Items schema in the database.
Did you get any errors during the startup?

However, to be honest, by now you'd be better served by simply using [apollo](https://www.apollographql.com/) or some other tool that makes Graphql easy for you, and the latest version of Sequelize or other ORM tools, rather than making this much outdated code base work.

**Comment by camous** [comment]
Hi @batjko , really appreciate your response time for a code base of 3 years.

I was able to make it works few minutes ago, just the name wasn't part of the initial schema.
![image](https://user-images.githubusercontent.com/8566299/52881994-95bb0e00-3166-11e9-8f54-d2c34b1f94b6.png)

thanks for your redirection to Sequelize (already spotted following your documentation) or apollo, I'm in pure investigation phase and looking for best approach on my needs. 

I'm not looking for performance but narrowing down possibility on finding a common query syntax (maintenance/operation/knowledge  is more important than performance or even stability for now ...) for various dependencies in heterogenous technologies (either database/input or language (nodejs/python/C#). mssql is one of input data I would address which your lib provide.

**Comment by batjko** [comment]
Cool. The graphql world (in javascript) is definitely converging on Apollo as the de-facto preferred set of libraries to write graphql servers and clients.

SQL libraries have more options that are largely comparable. Next to Sequelize, there's also Knex, both of which are fairly flexible and well-maintained, I think.

Good luck with your project!

**Comment by batjko** [comment]
I've just pushed v2 of this repo, which rebuilt it all from scratch.
I'll close this off as relating to the previous code base, but please don't hesitate to create a new issue should there be any other problems or questions.
